import type { Product, PhilippineLocation, Order } from "@/lib/types"
import { productApi } from "@/lib/api"

// Mock product data
const products: Product[] = [
  // Laptops
  {
    id: "laptop-1",
    name: "TechPro UltraBook X5",
    description: "Powerful and lightweight laptop for professionals",
    fullDescription:
      "The TechPro UltraBook X5 is designed for professionals who need power and portability. With its 11th Gen Intel Core i7 processor, 16GB RAM, and 512GB SSD, this laptop handles demanding tasks with ease. The 14-inch 4K display delivers stunning visuals, while the all-day battery life ensures you stay productive wherever you go.",
    price: 65999,
    originalPrice: 72999,
    discount: 10,
    rating: 4.7,
    stock: 15,
    sold: 85,
    category: "Laptops",
    brand: "TechPro",
    sku: "TP-UB-X5-001",
    images: [
      "https://images.pexels.com/photos/18105/pexels-photo.jpg?auto=compress&cs=tinysrgb&w=1260&h=750&dpr=2",
      "https://images.pexels.com/photos/303383/pexels-photo-303383.jpeg?auto=compress&cs=tinysrgb&w=1260&h=750&dpr=2",
      "https://images.pexels.com/photos/1229861/pexels-photo-1229861.jpeg?auto=compress&cs=tinysrgb&w=1260&h=750&dpr=2",
      "https://images.pexels.com/photos/1181675/pexels-photo-1181675.jpeg?auto=compress&cs=tinysrgb&w=1260&h=750&dpr=2",
    ],
    features: [
      "11th Gen Intel Core i7 processor",
      "16GB DDR4 RAM",
      "512GB NVMe SSD",
      "14-inch 4K Ultra HD Display",
      "Backlit Keyboard",
      "Windows 11 Pro",
      "Up to 12 hours battery life",
      "Fingerprint Reader",
    ],
    specifications: {
      Processor: "Intel Core i7-1165G7",
      Memory: "16GB DDR4 3200MHz",
      Storage: "512GB PCIe NVMe SSD",
      Display: "14-inch 4K (3840 x 2160) IPS",
      Graphics: "Intel Iris Xe Graphics",
      "Operating System": "Windows 11 Pro",
      Battery: "65Wh, up to 12 hours",
      Weight: "1.3 kg",
      Dimensions: "323 x 218 x 15.9 mm",
      Ports: "2x Thunderbolt 4, 1x USB 3.2, HDMI, 3.5mm audio jack",
      Wireless: "Wi-Fi 6, Bluetooth 5.1",
    },
    reviews: [
      {
        id: "r1",
        name: "John D.",
        rating: 5,
        comment:
          "Excellent performance and battery life. The display is stunning and the keyboard is comfortable for long typing sessions.",
        date: "2023-11-15",
      },
      {
        id: "r2",
        name: "Sarah M.",
        rating: 4,
        comment:
          "Great laptop overall. Fast and reliable. The only downside is that it runs a bit hot under heavy load.",
        date: "2023-10-22",
      },
      {
        id: "r3",
        name: "Michael T.",
        rating: 5,
        comment: "Perfect for my work needs. The build quality is exceptional and the performance is top-notch.",
        date: "2023-09-30",
      },
    ],
    isNew: false,
    featured: true,
    trending: true,
    createdAt: "2023-06-15",
  },
  {
    id: "laptop-2",
    name: "GameForce Titan RTX",
    description: "Ultimate gaming laptop with RTX graphics",
    fullDescription:
      "Dominate the gaming world with the GameForce Titan RTX. Powered by the latest AMD Ryzen 9 processor and NVIDIA RTX 3080 graphics, this beast delivers uncompromising performance for the most demanding games. The 17.3-inch 165Hz display with 3ms response time ensures smooth gameplay, while the RGB keyboard adds style to your gaming setup.",
    price: 129999,
    originalPrice: 149999,
    discount: 13,
    rating: 4.9,
    stock: 8,
    sold: 42,
    category: "Laptops",
    brand: "GameForce",
    sku: "GF-TI-RTX-002",
    images: [
      "https://images.pexels.com/photos/1181675/pexels-photo-1181675.jpeg?auto=compress&cs=tinysrgb&w=1260&h=750&dpr=2",
      "https://images.pexels.com/photos/129208/pexels-photo-129208.jpeg?auto=compress&cs=tinysrgb&w=1260&h=750&dpr=2",
      "https://images.pexels.com/photos/7974/pexels-photo.jpg?auto=compress&cs=tinysrgb&w=1260&h=750&dpr=2",
      "https://images.pexels.com/photos/4158/apple-iphone-smartphone-desk.jpg?auto=compress&cs=tinysrgb&w=1260&h=750&dpr=2",
    ],
    features: [
      "AMD Ryzen 9 5900HX processor",
      "NVIDIA GeForce RTX 3080 16GB",
      "32GB DDR4 RAM",
      "1TB NVMe SSD",
      "17.3-inch 165Hz QHD Display",
      "Per-key RGB Keyboard",
      "Advanced Cooling System",
      "Windows 11 Home",
    ],
    specifications: {
      Processor: "AMD Ryzen 9 5900HX (8-core, up to 4.6GHz)",
      Memory: "32GB DDR4 3200MHz (2x16GB)",
      Storage: "1TB PCIe NVMe SSD",
      Display: "17.3-inch QHD (2560 x 1440) 165Hz, 3ms response time",
      Graphics: "NVIDIA GeForce RTX 3080 16GB GDDR6",
      "Operating System": "Windows 11 Home",
      Battery: "90Wh, up to 5 hours gaming",
      Weight: "2.9 kg",
      Dimensions: "395 x 282 x 23 mm",
      Ports: "3x USB 3.2, 1x USB-C, HDMI, Mini DisplayPort, RJ-45, 3.5mm audio jack",
      Wireless: "Wi-Fi 6, Bluetooth 5.2",
    },
    reviews: [
      {
        id: "r4",
        name: "Alex G.",
        rating: 5,
        comment: "This is a gaming beast! Runs every game I throw at it on max settings without breaking a sweat.",
        date: "2023-11-05",
      },
      {
        id: "r5",
        name: "Jessica K.",
        rating: 5,
        comment: "Worth every peso. The display is gorgeous and the performance is unmatched.",
        date: "2023-10-18",
      },
      {
        id: "r6",
        name: "Ryan P.",
        rating: 4,
        comment:
          "Amazing gaming performance. The only downside is the weight and battery life, but that's expected for a gaming laptop of this caliber.",
        date: "2023-09-25",
      },
    ],
    isNew: true,
    featured: true,
    trending: true,
    createdAt: "2023-08-10",
  },
  {
    id: "laptop-3",
    name: "EcoBook Air 13",
    description: "Eco-friendly, ultra-thin laptop with all-day battery",
    fullDescription:
      "The EcoBook Air 13 combines sustainability with performance. Made with recycled aluminum and plastic-free packaging, this laptop is as good for the environment as it is for your productivity. The energy-efficient Intel Core i5 processor and 8GB RAM provide smooth performance for everyday tasks, while the 13.3-inch Retina display delivers crisp visuals.",
    price: 49999,
    originalPrice: 54999,
    discount: 9,
    rating: 4.5,
    stock: 22,
    sold: 68,
    category: "Laptops",
    brand: "EcoTech",
    sku: "ET-EB-A13-003",
    images: [
      "https://images.pexels.com/photos/7974/pexels-photo.jpg?auto=compress&cs=tinysrgb&w=1260&h=750&dpr=2",
      "https://images.pexels.com/photos/18105/pexels-photo.jpg?auto=compress&cs=tinysrgb&w=1260&h=750&dpr=2",
      "https://images.pexels.com/photos/303383/pexels-photo-303383.jpeg?auto=compress&cs=tinysrgb&w=1260&h=750&dpr=2",
      "https://images.pexels.com/photos/1229861/pexels-photo-1229861.jpeg?auto=compress&cs=tinysrgb&w=1260&h=750&dpr=2",
    ],
    features: [
      "Intel Core i5 processor",
      "8GB unified memory",
      "256GB SSD storage",
      "13.3-inch Retina display",
      "Made with 100% recycled aluminum",
      "Plastic-free packaging",
      "Up to 18 hours battery life",
      "Touch ID",
    ],
    specifications: {
      Processor: "Intel Core i5 (10th Gen)",
      Memory: "8GB unified memory",
      Storage: "256GB SSD",
      Display: "13.3-inch Retina display (2560 x 1600)",
      Graphics: "Intel Iris Plus Graphics",
      "Operating System": "macOS",
      Battery: "Up to 18 hours",
      Weight: "1.29 kg",
      Dimensions: "304.1 x 212.4 x 16.1 mm",
      Ports: "2x Thunderbolt 3 (USB-C)",
      Wireless: "Wi-Fi 6, Bluetooth 5.0",
    },
    reviews: [
      {
        id: "r7",
        name: "Emma L.",
        rating: 5,
        comment: "Love the eco-friendly approach! The laptop is lightweight, fast, and the battery lasts all day.",
        date: "2023-11-10",
      },
      {
        id: "r8",
        name: "David R.",
        rating: 4,
        comment: "Great laptop for everyday use. The display is beautiful and the build quality is excellent.",
        date: "2023-10-05",
      },
      {
        id: "r9",
        name: "Sophia C.",
        rating: 4,
        comment: "Solid performance and I appreciate the sustainability focus. Would like more ports though.",
        date: "2023-09-18",
      },
    ],
    isNew: false,
    featured: false,
    trending: false,
    createdAt: "2023-05-20",
  },

  // Phones
  {
    id: "phone-1",
    name: "PixelMax Pro 5G",
    description: "Flagship smartphone with professional-grade camera system",
    fullDescription:
      "The PixelMax Pro 5G redefines mobile photography with its revolutionary quad-camera system. Capture stunning photos in any lighting condition with the 108MP main sensor, ultra-wide lens, telephoto lens, and macro camera. Powered by the latest Snapdragon processor and 12GB RAM, this phone handles everything from gaming to multitasking with ease. The 6.7-inch AMOLED display with 120Hz refresh rate delivers smooth, vibrant visuals.",
    price: 54999,
    originalPrice: 59999,
    discount: 8,
    rating: 4.8,
    stock: 25,
    sold: 95,
    category: "Phones",
    brand: "PixelMax",
    sku: "PM-PRO-5G-001",
    images: [
      "https://images.pexels.com/photos/47261/pexels-photo-47261.jpeg?auto=compress&cs=tinysrgb&w=1260&h=750&dpr=2",
      "https://images.pexels.com/photos/699122/pexels-photo-699122.jpeg?auto=compress&cs=tinysrgb&w=1260&h=750&dpr=2",
      "https://images.pexels.com/photos/607812/pexels-photo-607812.jpeg?auto=compress&cs=tinysrgb&w=1260&h=750&dpr=2",
      "https://images.pexels.com/photos/1092644/pexels-photo-1092644.jpeg?auto=compress&cs=tinysrgb&w=1260&h=750&dpr=2",
    ],
    features: [
      "Snapdragon 8 Gen 1 processor",
      "12GB LPDDR5 RAM",
      "256GB UFS 3.1 storage",
      "6.7-inch AMOLED 120Hz display",
      "Quad camera system (108MP main)",
      "5000mAh battery",
      "65W fast charging",
      "Android 12",
    ],
    specifications: {
      Processor: "Snapdragon 8 Gen 1",
      Memory: "12GB LPDDR5",
      Storage: "256GB UFS 3.1",
      Display: "6.7-inch AMOLED, 120Hz, HDR10+",
      Resolution: "3200 x 1440 pixels",
      "Main Camera": "108MP, f/1.8, OIS",
      "Ultra-wide": "48MP, f/2.2, 120° FOV",
      Telephoto: "12MP, f/2.4, 5x optical zoom",
      Macro: "5MP, f/2.4",
      "Front Camera": "32MP, f/2.0",
      Battery: "5000mAh",
      Charging: "65W wired, 30W wireless",
      OS: "Android 12",
      Dimensions: "163.6 x 76.5 x 8.9 mm",
      Weight: "198g",
    },
    reviews: [
      {
        id: "r10",
        name: "James H.",
        rating: 5,
        comment: "Best camera on a smartphone, period. The photos are incredible, especially in low light.",
        date: "2023-11-12",
      },
      {
        id: "r11",
        name: "Olivia W.",
        rating: 5,
        comment: "The display is gorgeous and the performance is top-notch. Battery life is impressive too.",
        date: "2023-10-28",
      },
      {
        id: "r12",
        name: "Daniel K.",
        rating: 4,
        comment: "Great phone overall. The camera system is amazing, but the software could use some refinement.",
        date: "2023-09-15",
      },
    ],
    isNew: true,
    featured: true,
    trending: true,
    createdAt: "2023-07-05",
  },
  {
    id: "phone-2",
    name: "Galaxy Ultra S23",
    description: "Premium Android smartphone with S Pen support",
    fullDescription:
      "The Galaxy Ultra S23 is the ultimate productivity powerhouse. With S Pen support, you can take notes, sketch, and navigate with precision. The 6.8-inch Dynamic AMOLED 2X display offers stunning colors and deep blacks, while the 200MP camera system captures incredible detail. Powered by the Snapdragon 8 Gen 2 processor and 12GB RAM, this phone handles anything you throw at it.",
    price: 69999,
    originalPrice: 74999,
    discount: 7,
    rating: 4.7,
    stock: 18,
    sold: 82,
    category: "Phones",
    brand: "Samsung",
    sku: "SS-GU-S23-002",
    images: [
      "https://images.pexels.com/photos/404280/pexels-photo-404280.jpeg?auto=compress&cs=tinysrgb&w=1260&h=750&dpr=2",
      "https://images.pexels.com/photos/1092644/pexels-photo-1092644.jpeg?auto=compress&cs=tinysrgb&w=1260&h=750&dpr=2",
      "https://images.pexels.com/photos/607812/pexels-photo-607812.jpeg?auto=compress&cs=tinysrgb&w=1260&h=750&dpr=2",
      "https://images.pexels.com/photos/699122/pexels-photo-699122.jpeg?auto=compress&cs=tinysrgb&w=1260&h=750&dpr=2",
    ],
    features: [
      "Snapdragon 8 Gen 2 processor",
      "12GB RAM",
      "512GB storage",
      "6.8-inch Dynamic AMOLED 2X display",
      "200MP main camera",
      "5000mAh battery",
      "45W fast charging",
      "S Pen included",
    ],
    specifications: {
      Processor: "Snapdragon 8 Gen 2",
      Memory: "12GB LPDDR5X",
      Storage: "512GB UFS 4.0",
      Display: "6.8-inch Dynamic AMOLED 2X, 120Hz, HDR10+",
      Resolution: "3088 x 1440 pixels",
      "Main Camera": "200MP, f/1.7, OIS",
      "Ultra-wide": "12MP, f/2.2, 120° FOV",
      "Telephoto 1": "10MP, f/2.4, 3x optical zoom",
      "Telephoto 2": "10MP, f/4.9, 10x optical zoom",
      "Front Camera": "12MP, f/2.2",
      Battery: "5000mAh",
      Charging: "45W wired, 15W wireless",
      OS: "Android 13",
      Dimensions: "163.4 x 78.1 x 8.9 mm",
      Weight: "233g",
    },
    reviews: [
      {
        id: "r13",
        name: "Thomas B.",
        rating: 5,
        comment:
          "The S Pen is a game-changer for productivity. The camera is also incredible, especially the zoom capabilities.",
        date: "2023-11-08",
      },
      {
        id: "r14",
        name: "Ava J.",
        rating: 4,
        comment: "Beautiful display and excellent performance. The battery life could be better though.",
        date: "2023-10-20",
      },
      {
        id: "r15",
        name: "Noah L.",
        rating: 5,
        comment:
          "This phone does everything exceptionally well. The camera system is versatile and the S Pen is useful for work.",
        date: "2023-09-12",
      },
    ],
    isNew: true,
    featured: true,
    trending: true,
    createdAt: "2023-07-15",
  },
  {
    id: "phone-3",
    name: "iPhoneX Pro Max",
    description: "Apple's flagship smartphone with advanced camera system",
    fullDescription:
      "The iPhoneX Pro Max sets a new standard for smartphone photography with its triple-camera system and computational photography capabilities. The 6.7-inch Super Retina XDR display delivers true-to-life colors and incredible brightness, while the A16 Bionic chip provides unmatched performance and efficiency. With up to 1TB of storage, you'll never run out of space for your photos, videos, and apps.",
    price: 79999,
    originalPrice: 84999,
    discount: 6,
    rating: 4.9,
    stock: 12,
    sold: 108,
    category: "Phones",
    brand: "Apple",
    sku: "AP-IPX-PM-003",
    images: [
      "https://images.pexels.com/photos/699122/pexels-photo-699122.jpeg?auto=compress&cs=tinysrgb&w=1260&h=750&dpr=2",
      "https://images.pexels.com/photos/47261/pexels-photo-47261.jpeg?auto=compress&cs=tinysrgb&w=1260&h=750&dpr=2",
      "https://images.pexels.com/photos/1092644/pexels-photo-1092644.jpeg?auto=compress&cs=tinysrgb&w=1260&h=750&dpr=2",
      "https://images.pexels.com/photos/607812/pexels-photo-607812.jpeg?auto=compress&cs=tinysrgb&w=1260&h=750&dpr=2",
    ],
    features: [
      "A16 Bionic chip",
      "6GB RAM",
      "1TB storage",
      "6.7-inch Super Retina XDR display",
      "Triple camera system (48MP main)",
      "4323mAh battery",
      "MagSafe charging",
      "iOS 16",
    ],
    specifications: {
      Processor: "A16 Bionic",
      Memory: "6GB",
      Storage: "1TB",
      Display: "6.7-inch Super Retina XDR, 120Hz ProMotion",
      Resolution: "2796 x 1290 pixels",
      "Main Camera": "48MP, f/1.8, OIS",
      "Ultra-wide": "12MP, f/2.2, 120° FOV",
      Telephoto: "12MP, f/2.8, 3x optical zoom",
      "Front Camera": "12MP, f/1.9",
      Battery: "4323mAh",
      Charging: "27W wired, 15W MagSafe",
      OS: "iOS 16",
      Dimensions: "160.7 x 77.6 x 7.9 mm",
      Weight: "240g",
    },
    reviews: [
      {
        id: "r16",
        name: "Sophia R.",
        rating: 5,
        comment: "The camera system is incredible. The photos and videos I take with this phone look professional.",
        date: "2023-11-20",
      },
      {
        id: "r17",
        name: "Ethan M.",
        rating: 5,
        comment: "The display is stunning and the performance is flawless. Battery life easily lasts all day.",
        date: "2023-10-15",
      },
      {
        id: "r18",
        name: "Isabella C.",
        rating: 5,
        comment: "Worth every peso. The ecosystem integration with my other Apple devices is seamless.",
        date: "2023-09-05",
      },
    ],
    isNew: false,
    featured: true,
    trending: true,
    createdAt: "2023-06-25",
  },
  // New Arrivals - Phones
  {
    id: "phone-4",
    name: "UltraPhone 15 Pro",
    description: "Latest flagship smartphone with advanced camera system and AI features",
    fullDescription:
      "The UltraPhone 15 Pro represents the pinnacle of smartphone technology. Featuring the latest A17 Pro chip, it delivers unprecedented performance for gaming, photography, and everyday tasks. The revolutionary camera system includes a 48MP main sensor with advanced computational photography, allowing you to capture professional-quality photos in any lighting condition. With all-day battery life and the fastest charging in any smartphone, you'll never be left without power.",
    price: 69999,
    originalPrice: 74999,
    discount: 7,
    rating: 4.9,
    stock: 20,
    sold: 45,
    category: "Phones",
    brand: "UltraTech",
    sku: "UT-UP-15P-001",
    images: [
      "https://images.pexels.com/photos/1042143/pexels-photo-1042143.jpeg?auto=compress&cs=tinysrgb&w=1260&h=750&dpr=2",
      "https://images.pexels.com/photos/699122/pexels-photo-699122.jpeg?auto=compress&cs=tinysrgb&w=1260&h=750&dpr=2",
      "https://images.pexels.com/photos/1092644/pexels-photo-1092644.jpeg?auto=compress&cs=tinysrgb&w=1260&h=750&dpr=2",
      "https://images.pexels.com/photos/47261/pexels-photo-47261.jpeg?auto=compress&cs=tinysrgb&w=1260&h=750&dpr=2",
    ],
    features: [
      "A17 Pro chip",
      "6.7-inch Super Retina XDR display",
      "48MP main camera with 4K video",
      "5G connectivity",
      "All-day battery life",
      "Fast charging",
      "Titanium design",
      "Advanced AI features",
    ],
    specifications: {
      Processor: "A17 Pro chip",
      Memory: "8GB RAM",
      Storage: "256GB, 512GB, or 1TB",
      Display: "6.7-inch Super Retina XDR, 120Hz ProMotion",
      Resolution: "2796 x 1290 pixels",
      "Main Camera": "48MP, f/1.8, OIS",
      "Ultra-wide": "12MP, f/2.2, 120° FOV",
      Telephoto: "12MP, f/2.8, 3x optical zoom",
      "Front Camera": "12MP, f/1.9",
      Battery: "4400mAh",
      Charging: "30W wired, 15W wireless",
      OS: "iOS 17",
      Dimensions: "159.9 x 76.7 x 8.25 mm",
      Weight: "221g",
    },
    reviews: [
      {
        id: "r49",
        name: "Olivia P.",
        rating: 5,
        comment: "The camera system is incredible. Photos look professional even in low light conditions.",
        date: "2023-11-15",
      },
      {
        id: "r50",
        name: "Nathan K.",
        rating: 5,
        comment: "The A17 Pro chip is blazing fast. Games run smoothly and the battery lasts all day.",
        date: "2023-11-02",
      },
      {
        id: "r51",
        name: "Rachel M.",
        rating: 4,
        comment: "Beautiful design and excellent performance. The only downside is the price, but it's worth it.",
        date: "2023-10-20",
      },
    ],
    isNew: true,
    featured: true,
    trending: true,
    createdAt: "2023-10-15",
  },

  // Accessories
  {
    id: "accessory-1",
    name: "SoundWave Pro Wireless Earbuds",
    description: "Premium wireless earbuds with active noise cancellation",
    fullDescription:
      "Experience immersive sound with the SoundWave Pro Wireless Earbuds. These premium earbuds feature active noise cancellation to block out distractions, while the transparency mode lets you hear your surroundings when needed. With 8 hours of battery life (24 hours with the charging case), you can enjoy your music all day long. The ergonomic design ensures a comfortable fit, and the IPX7 water resistance makes them perfect for workouts.",
    price: 8999,
    originalPrice: 10999,
    discount: 18,
    rating: 4.6,
    stock: 35,
    sold: 120,
    category: "Accessories",
    brand: "SoundWave",
    sku: "SW-PRO-WE-001",
    images: [
      "https://images.pexels.com/photos/3780681/pexels-photo-3780681.jpeg?auto=compress&cs=tinysrgb&w=1260&h=750&dpr=2",
      "https://images.pexels.com/photos/1037999/pexels-photo-1037999.jpeg?auto=compress&cs=tinysrgb&w=1260&h=750&dpr=2",
      "https://images.pexels.com/photos/1649771/pexels-photo-1649771.jpeg?auto=compress&cs=tinysrgb&w=1260&h=750&dpr=2",
      "https://images.pexels.com/photos/3394666/pexels-photo-3394666.jpeg?auto=compress&cs=tinysrgb&w=1260&h=750&dpr=2",
    ],
    features: [
      "Active Noise Cancellation",
      "Transparency Mode",
      "8 hours battery life (24 hours with case)",
      "IPX7 water resistance",
      "Touch controls",
      "Wireless charging case",
      "Bluetooth 5.2",
      "Voice assistant support",
    ],
    specifications: {
      Driver: "11mm dynamic driver",
      Connectivity: "Bluetooth 5.2",
      "Battery Life": "8 hours (earbuds), 24 hours (with case)",
      Charging: "USB-C, Qi wireless",
      "Water Resistance": "IPX7",
      "Noise Cancellation": "Hybrid ANC",
      Microphones: "4 beamforming mics",
      Weight: "5.4g (each earbud), 58g (case)",
      Dimensions: "Case: 62.5 x 46.5 x 24.5 mm",
      Codecs: "SBC, AAC, aptX Adaptive",
    },
    reviews: [
      {
        id: "r19",
        name: "Lucas P.",
        rating: 5,
        comment:
          "The noise cancellation is impressive and the sound quality is excellent. Very comfortable for long listening sessions.",
        date: "2023-11-18",
      },
      {
        id: "r20",
        name: "Mia K.",
        rating: 4,
        comment: "Great earbuds overall. The battery life is as advertised and they stay secure during workouts.",
        date: "2023-10-25",
      },
      {
        id: "r21",
        name: "Jackson T.",
        rating: 5,
        comment:
          "The sound quality is amazing for the price. The noise cancellation works well even in noisy environments.",
        date: "2023-09-10",
      },
    ],
    isNew: false,
    featured: true,
    trending: false,
    createdAt: "2023-05-10",
  },
  {
    id: "accessory-2",
    name: "PowerBank Ultra 26800mAh",
    description: "High-capacity power bank with fast charging",
    fullDescription:
      "Never run out of battery again with the PowerBank Ultra 26800mAh. This high-capacity power bank can charge your smartphone up to 8 times or your tablet up to 3 times. With 65W Power Delivery and Quick Charge 4.0 support, it charges your devices at maximum speed. The digital display shows the remaining battery percentage, so you always know how much power you have left. The compact design makes it easy to carry in your bag or pocket.",
    price: 3499,
    originalPrice: 3999,
    discount: 13,
    rating: 4.7,
    stock: 50,
    sold: 85,
    category: "Accessories",
    brand: "PowerTech",
    sku: "PT-PB-U26-002",
    images: [
      "https://images.pexels.com/photos/4526407/pexels-photo-4526407.jpeg?auto=compress&cs=tinysrgb&w=1260&h=750&dpr=2",
      "https://images.pexels.com/photos/4792733/pexels-photo-4792733.jpeg?auto=compress&cs=tinysrgb&w=1260&h=750&dpr=2",
      "https://images.pexels.com/photos/4526406/pexels-photo-4526406.jpeg?auto=compress&cs=tinysrgb&w=1260&h=750&dpr=2",
      "https://images.pexels.com/photos/4526408/pexels-photo-4526408.jpeg?auto=compress&cs=tinysrgb&w=1260&h=750&dpr=2",
    ],
    features: [
      "26800mAh capacity",
      "65W Power Delivery",
      "Quick Charge 4.0",
      "Digital display",
      "3 output ports (2x USB-A, 1x USB-C)",
      "Pass-through charging",
      "Airline approved",
      "Compact design",
    ],
    specifications: {
      Capacity: "26800mAh / 99.16Wh",
      Input: "USB-C PD (5V/3A, 9V/3A, 12V/3A, 15V/3A, 20V/3.25A)",
      "Output 1": "USB-C PD (5V/3A, 9V/3A, 12V/3A, 15V/3A, 20V/3.25A)",
      "Output 2": "USB-A QC 4.0 (5V/4.5A, 9V/3A, 12V/2.5A)",
      "Output 3": "USB-A (5V/2.4A)",
      "Max Output": "65W",
      "Recharge Time": "3.5 hours (with 65W PD charger)",
      Display: "Digital LED percentage display",
      Dimensions: "158 x 75 x 27 mm",
      Weight: "430g",
    },
    reviews: [
      {
        id: "r22",
        name: "Aiden R.",
        rating: 5,
        comment: "This power bank is a lifesaver! The capacity is huge and it charges my devices quickly.",
        date: "2023-11-15",
      },
      {
        id: "r23",
        name: "Zoe L.",
        rating: 4,
        comment: "Great power bank with fast charging. The digital display is very useful. A bit heavy though.",
        date: "2023-10-22",
      },
      {
        id: "r24",
        name: "Benjamin S.",
        rating: 5,
        comment:
          "Perfect for travel. I can charge my phone, tablet, and laptop multiple times without needing to find an outlet.",
        date: "2023-09-08",
      },
    ],
    isNew: false,
    featured: false,
    trending: true,
    createdAt: "2023-06-05",
  },
  {
    id: "accessory-3",
    name: "SmartWatch Pro 5",
    description: "Advanced smartwatch with health monitoring and GPS",
    fullDescription:
      "The SmartWatch Pro 5 is your perfect health and fitness companion. With advanced health monitoring features like ECG, blood oxygen measurement, and sleep tracking, you can keep an eye on your wellbeing 24/7. The built-in GPS accurately tracks your outdoor activities, while the 5ATM water resistance makes it suitable for swimming. With up to 14 days of battery life, you don't need to worry about frequent charging.",
    price: 12999,
    originalPrice: 14999,
    discount: 13,
    rating: 4.8,
    stock: 28,
    sold: 72,
    category: "Accessories",
    brand: "TechFit",
    sku: "TF-SW-P5-003",
    images: [
      "https://images.pexels.com/photos/437037/pexels-photo-437037.jpeg?auto=compress&cs=tinysrgb&w=1260&h=750&dpr=2",
      "https://images.pexels.com/photos/393047/pexels-photo-393047.jpeg?auto=compress&cs=tinysrgb&w=1260&h=750&dpr=2",
      "https://images.pexels.com/photos/267394/pexels-photo-267394.jpeg?auto=compress&cs=tinysrgb&w=1260&h=750&dpr=2",
      "https://images.pexels.com/photos/236915/pexels-photo-236915.jpeg?auto=compress&cs=tinysrgb&w=1260&h=750&dpr=2",
    ],
    features: [
      "1.4-inch AMOLED display",
      "ECG and blood oxygen monitoring",
      "Sleep tracking",
      "Built-in GPS",
      "5ATM water resistance",
      "14 days battery life",
      "100+ sport modes",
      "Bluetooth calling",
    ],
    specifications: {
      Display: "1.4-inch AMOLED, 454 x 454 pixels",
      Sensors: "Heart rate, SpO2, accelerometer, gyroscope, barometer, ambient light",
      Connectivity: "Bluetooth 5.2, Wi-Fi, GPS, GLONASS, Galileo",
      "Water Resistance": "5ATM (50 meters)",
      Battery: "450mAh, up to 14 days (typical use)",
      Charging: "Magnetic charging cable",
      Compatibility: "Android 6.0+, iOS 12.0+",
      Dimensions: "46 x 46 x 11 mm",
      Weight: "48g (without strap)",
      Strap: "Silicone, 22mm width",
    },
    reviews: [
      {
        id: "r25",
        name: "Harper W.",
        rating: 5,
        comment:
          "Amazing smartwatch with accurate health tracking. The battery life is impressive - almost two weeks on a single charge!",
        date: "2023-11-10",
      },
      {
        id: "r26",
        name: "Leo J.",
        rating: 5,
        comment: "The fitness tracking features are comprehensive and the GPS is very accurate. Great value for money.",
        date: "2023-10-18",
      },
      {
        id: "r27",
        name: "Aria M.",
        rating: 4,
        comment:
          "Love this watch! The health monitoring features are excellent. The only downside is that the app could be more intuitive.",
        date: "2023-09-05",
      },
    ],
    isNew: true,
    featured: true,
    trending: true,
    createdAt: "2023-07-20",
  },

  // Tablets
  {
    id: "tablet-1",
    name: "Galaxy Tab Ultra",
    description: "Premium Android tablet with S Pen and keyboard support",
    fullDescription:
      "The Galaxy Tab Ultra is the ultimate productivity tablet. With its stunning 12.4-inch Super AMOLED display and powerful Snapdragon processor, it's perfect for work and entertainment. The included S Pen offers precise control for note-taking and drawing, while the optional keyboard cover transforms it into a laptop replacement. With DeX mode, you can enjoy a desktop-like experience when you need to get serious work done.",
    price: 49999,
    originalPrice: 54999,
    discount: 9,
    rating: 4.8,
    stock: 20,
    sold: 65,
    category: "Tablets",
    brand: "Samsung",
    sku: "SS-GT-U-001",
    images: [
      "https://images.pexels.com/photos/1334597/pexels-photo-1334597.jpeg?auto=compress&cs=tinysrgb&w=1260&h=750&dpr=2",
      "https://images.pexels.com/photos/1334598/pexels-photo-1334598.jpeg?auto=compress&cs=tinysrgb&w=1260&h=750&dpr=2",
      "https://images.pexels.com/photos/1716539/pexels-photo-1716539.jpeg?auto=compress&cs=tinysrgb&w=1260&h=750&dpr=2",
      "https://images.pexels.com/photos/1432675/pexels-photo-1432675.jpeg?auto=compress&cs=tinysrgb&w=1260&h=750&dpr=2",
    ],
    features: [
      "12.4-inch Super AMOLED display",
      "Snapdragon 8 Gen 1 processor",
      "8GB RAM, 256GB storage",
      "S Pen included",
      "Optional keyboard cover",
      "DeX mode",
      "10,090mAh battery",
      "Android 13",
    ],
    specifications: {
      Display: "12.4-inch Super AMOLED, 120Hz, HDR10+",
      Resolution: "2800 x 1752 pixels",
      Processor: "Snapdragon 8 Gen 1",
      Memory: "8GB LPDDR5",
      Storage: "256GB UFS 3.1, expandable via microSD",
      "Rear Camera": "13MP wide, 6MP ultra-wide",
      "Front Camera": "12MP ultra-wide",
      Battery: "10,090mAh",
      Charging: "45W fast charging",
      OS: "Android 13",
      Dimensions: "285.4 x 185.0 x 5.7 mm",
      Weight: "575g",
      Connectivity: "Wi-Fi 6E, Bluetooth 5.2, USB-C 3.2",
    },
    reviews: [
      {
        id: "r28",
        name: "Mason B.",
        rating: 5,
        comment:
          "This tablet is a powerhouse. The display is gorgeous and the S Pen is incredibly responsive. Perfect for productivity and entertainment.",
        date: "2023-11-05",
      },
      {
        id: "r29",
        name: "Scarlett P.",
        rating: 5,
        comment:
          "The DeX mode transforms this tablet into a laptop replacement. The keyboard cover is excellent for typing.",
        date: "2023-10-12",
      },
      {
        id: "r30",
        name: "Elijah N.",
        rating: 4,
        comment:
          "Great tablet with excellent performance. The only downside is the price, but you get what you pay for.",
        date: "2023-09-20",
      },
    ],
    isNew: false,
    featured: true,
    trending: true,
    createdAt: "2023-06-10",
  },
  {
    id: "tablet-2",
    name: "iPad Pro M2",
    description: "Apple's most powerful tablet with M2 chip",
    fullDescription:
      "The iPad Pro M2 redefines what a tablet can do. Powered by the M2 chip, it delivers desktop-class performance in a thin and light design. The 12.9-inch Liquid Retina XDR display offers stunning brightness and contrast, making it perfect for creative professionals. With support for Apple Pencil and Magic Keyboard, it's a versatile tool for productivity, creativity, and entertainment.",
    price: 59999,
    originalPrice: 64999,
    discount: 8,
    rating: 4.9,
    stock: 15,
    sold: 78,
    category: "Tablets",
    brand: "Apple",
    sku: "AP-IP-M2-002",
    images: [
      "https://images.pexels.com/photos/1716539/pexels-photo-1716539.jpeg?auto=compress&cs=tinysrgb&w=1260&h=750&dpr=2",
      "https://images.pexels.com/photos/1334597/pexels-photo-1334597.jpeg?auto=compress&cs=tinysrgb&w=1260&h=750&dpr=2",
      "https://images.pexels.com/photos/1334598/pexels-photo-1334598.jpeg?auto=compress&cs=tinysrgb&w=1260&h=750&dpr=2",
      "https://images.pexels.com/photos/1432675/pexels-photo-1432675.jpeg?auto=compress&cs=tinysrgb&w=1260&h=750&dpr=2",
    ],
    features: [
      "12.9-inch Liquid Retina XDR display",
      "M2 chip",
      "16GB RAM, 1TB storage",
      "Apple Pencil support",
      "Magic Keyboard support",
      "Thunderbolt / USB 4",
      "Face ID",
      "iPadOS 16",
    ],
    specifications: {
      Display: "12.9-inch Liquid Retina XDR, 120Hz ProMotion",
      Resolution: "2732 x 2048 pixels",
      Processor: "Apple M2 (8-core CPU, 10-core GPU)",
      Memory: "16GB",
      Storage: "1TB",
      "Rear Camera": "12MP wide, 10MP ultra-wide, LiDAR Scanner",
      "Front Camera": "12MP ultra-wide with Center Stage",
      Battery: "Up to 10 hours",
      Charging: "USB-C (Thunderbolt / USB 4)",
      OS: "iPadOS 16",
      Dimensions: "280.6 x 214.9 x 6.4 mm",
      Weight: "682g (Wi-Fi)",
      Connectivity: "Wi-Fi 6E, Bluetooth 5.3, USB-C",
    },
    reviews: [
      {
        id: "r31",
        name: "Lily R.",
        rating: 5,
        comment: "The M2 chip makes this iPad incredibly fast. The display is stunning for photo and video editing.",
        date: "2023-11-15",
      },
      {
        id: "r32",
        name: "Gabriel T.",
        rating: 5,
        comment:
          "This is more powerful than many laptops. The ecosystem integration with my other Apple devices is seamless.",
        date: "2023-10-28",
      },
      {
        id: "r33",
        name: "Chloe H.",
        rating: 5,
        comment: "Worth every peso for creative professionals. The Apple Pencil is incredibly precise for digital art.",
        date: "2023-09-14",
      },
    ],
    isNew: true,
    featured: true,
    trending: true,
    createdAt: "2023-07-25",
  },
  {
    id: "tablet-3",
    name: "Surface Pro 9",
    description: "Versatile Windows tablet with laptop performance",
    fullDescription:
      "The Surface Pro 9 offers the perfect balance of tablet portability and laptop performance. Running Windows 11, it gives you access to full desktop applications in a sleek, lightweight design. The 13-inch PixelSense Flow display with 120Hz refresh rate provides smooth visuals, while the Intel Core i7 processor delivers powerful performance for demanding tasks. With the detachable keyboard and Surface Slim Pen, you can work and create in any mode.",
    price: 79999,
    originalPrice: 84999,
    discount: 6,
    rating: 4.7,
    stock: 12,
    sold: 55,
    category: "Tablets",
    brand: "Microsoft",
    sku: "MS-SP-9-003",
    images: [
      "https://images.pexels.com/photos/1432675/pexels-photo-1432675.jpeg?auto=compress&cs=tinysrgb&w=1260&h=750&dpr=2",
      "https://images.pexels.com/photos/1716539/pexels-photo-1716539.jpeg?auto=compress&cs=tinysrgb&w=1260&h=750&dpr=2",
      "https://images.pexels.com/photos/1334597/pexels-photo-1334597.jpeg?auto=compress&cs=tinysrgb&w=1260&h=750&dpr=2",
      "https://images.pexels.com/photos/1334598/pexels-photo-1334598.jpeg?auto=compress&cs=tinysrgb&w=1260&h=750&dpr=2",
    ],
    features: [
      "13-inch PixelSense Flow display",
      "Intel Core i7-1255U processor",
      "16GB RAM, 512GB SSD",
      "Windows 11 Pro",
      "Surface Slim Pen support",
      "Detachable keyboard",
      "Up to 15.5 hours battery life",
      "Thunderbolt 4 ports",
    ],
    specifications: {
      Display: "13-inch PixelSense Flow, 120Hz",
      Resolution: "2880 x 1920 pixels",
      Processor: "Intel Core i7-1255U",
      Memory: "16GB LPDDR5",
      Storage: "512GB SSD",
      Graphics: "Intel Iris Xe",
      Camera: "Front: 1080p, Rear: 10MP",
      Battery: "Up to 15.5 hours",
      Ports: "2x Thunderbolt 4, Surface Connect port, 3.5mm headphone jack",
      OS: "Windows 11 Pro",
      Dimensions: "287 x 209 x 9.3 mm",
      Weight: "879g (without keyboard)",
      Connectivity: "Wi-Fi 6E, Bluetooth 5.1",
    },
    reviews: [
      {
        id: "r34",
        name: "Owen M.",
        rating: 5,
        comment: "The perfect 2-in-1 device. It's a full Windows PC when I need it and a tablet when I want to relax.",
        date: "2023-11-08",
      },
      {
        id: "r35",
        name: "Audrey K.",
        rating: 4,
        comment:
          "Great performance and versatility. The keyboard and pen are excellent, but sold separately which is a downside.",
        date: "2023-10-15",
      },
      {
        id: "r36",
        name: "Caleb S.",
        rating: 5,
        comment:
          "This replaced both my laptop and tablet. The 120Hz display is smooth and the battery life is impressive.",
        date: "2023-09-22",
      },
    ],
    isNew: false,
    featured: true,
    trending: false,
    createdAt: "2023-05-15",
  },

  // Smart Gadgets
  {
    id: "smart-1",
    name: "EchoSphere Smart Speaker",
    description: "Premium smart speaker with voice assistant and room-filling sound",
    fullDescription:
      "The EchoSphere Smart Speaker combines premium sound with intelligent voice control. With its 360-degree audio design, it fills any room with rich, detailed sound. The built-in voice assistant helps you control your smart home, play music, answer questions, and more, all hands-free. The sleek, modern design complements any home decor, while the privacy controls, including a physical microphone off button, give you peace of mind.",
    price: 7999,
    originalPrice: 9999,
    discount: 20,
    rating: 4.6,
    stock: 30,
    sold: 90,
    category: "Smart Gadgets",
    brand: "EchoTech",
    sku: "ET-ES-001",
    images: [
      "https://images.pexels.com/photos/4790255/pexels-photo-4790255.jpeg?auto=compress&cs=tinysrgb&w=1260&h=750&dpr=2",
      "https://images.pexels.com/photos/4790254/pexels-photo-4790254.jpeg?auto=compress&cs=tinysrgb&w=1260&h=750&dpr=2",
      "https://images.pexels.com/photos/4790253/pexels-photo-4790253.jpeg?auto=compress&cs=tinysrgb&w=1260&h=750&dpr=2",
      "https://images.pexels.com/photos/4790252/pexels-photo-4790252.jpeg?auto=compress&cs=tinysrgb&w=1260&h=750&dpr=2",
    ],
    features: [
      "360-degree room-filling sound",
      "Built-in voice assistant",
      "Smart home control",
      "Multi-room music",
      "Physical microphone off button",
      "Bluetooth connectivity",
      "3.5mm audio input",
      "Available in multiple colors",
    ],
    specifications: {
      Speakers: "3-inch woofer, dual 0.8-inch tweeters",
      Audio: "Dolby Audio processing",
      Microphones: "6-microphone array",
      Connectivity: "Dual-band Wi-Fi, Bluetooth 5.0, 3.5mm audio input",
      Power: "100-240V AC power supply",
      Dimensions: "144 x 144 x 175 mm",
      Weight: "1.5 kg",
      Colors: "Charcoal, Glacier White, Twilight Blue",
      Requirements: "Wi-Fi network, compatible mobile device",
      Warranty: "1-year limited warranty",
    },
    reviews: [
      {
        id: "r37",
        name: "Nora F.",
        rating: 5,
        comment:
          "The sound quality is impressive for its size. The voice assistant is responsive and understands Filipino accents well.",
        date: "2023-11-12",
      },
      {
        id: "r38",
        name: "Henry J.",
        rating: 4,
        comment:
          "Great smart speaker with excellent sound. The smart home integration works seamlessly with my lights and thermostat.",
        date: "2023-10-20",
      },
      {
        id: "r39",
        name: "Grace L.",
        rating: 5,
        comment:
          "This has become the center of our smart home. The sound quality is excellent and the voice recognition is accurate.",
        date: "2023-09-15",
      },
    ],
    isNew: false,
    featured: true,
    trending: true,
    createdAt: "2023-06-20",
  },
  {
    id: "smart-2",
    name: "SmartHome Security Camera",
    description: "Wireless security camera with 2K resolution and AI detection",
    fullDescription:
      "Keep your home safe with the SmartHome Security Camera. This wireless camera captures crystal-clear 2K video and uses AI to distinguish between people, vehicles, and animals, reducing false alerts. With color night vision, you can see details even in the dark. The weatherproof design makes it suitable for both indoor and outdoor use, while the rechargeable battery eliminates the need for wiring. Access live and recorded footage through the SmartHome app from anywhere.",
    price: 4999,
    originalPrice: 5999,
    discount: 17,
    rating: 4.7,
    stock: 45,
    sold: 75,
    category: "Smart Gadgets",
    brand: "SmartHome",
    sku: "SH-SC-002",
    images: [
      "https://images.pexels.com/photos/3952387/pexels-photo-3952387.jpeg?auto=compress&cs=tinysrgb&w=1260&h=750&dpr=2",
      "https://images.pexels.com/photos/3952386/pexels-photo-3952386.jpeg?auto=compress&cs=tinysrgb&w=1260&h=750&dpr=2",
      "https://images.pexels.com/photos/3952385/pexels-photo-3952385.jpeg?auto=compress&cs=tinysrgb&w=1260&h=750&dpr=2",
      "https://images.pexels.com/photos/3952384/pexels-photo-3952384.jpeg?auto=compress&cs=tinysrgb&w=1260&h=750&dpr=2",
    ],
    features: [
      "2K video resolution",
      "AI person, vehicle, and animal detection",
      "Color night vision",
      "Weatherproof design (IP65)",
      "Rechargeable battery (up to 6 months)",
      "Two-way audio",
      "Local and cloud storage options",
      "Works with Alexa and Google Assistant",
    ],
    specifications: {
      Resolution: "2K (2560 x 1440)",
      "Field of View": "160° diagonal",
      "Night Vision": "Color night vision up to 25 feet",
      Audio: "Full-duplex two-way audio with noise cancellation",
      "Weather Resistance": "IP65 (dust-tight and water-resistant)",
      Battery: "Rechargeable 6500mAh, up to 6 months per charge",
      Storage: "microSD card slot (up to 128GB), optional cloud storage",
      Connectivity: "2.4GHz Wi-Fi",
      Dimensions: "89 x 52 x 84.5 mm",
      Weight: "365g",
      "Operating Temperature": "-20°C to 45°C",
    },
    reviews: [
      {
        id: "r40",
        name: "Victor R.",
        rating: 5,
        comment:
          "The video quality is excellent and the AI detection works well. I no longer get alerts for every passing car.",
        date: "2023-11-10",
      },
      {
        id: "r41",
        name: "Penelope S.",
        rating: 4,
        comment: "Easy to install and the battery life is impressive. The app is intuitive and responsive.",
        date: "2023-10-18",
      },
      {
        id: "r42",
        name: "Isaac T.",
        rating: 5,
        comment:
          "Great security camera for the price. The color night vision is a game-changer for identifying details.",
        date: "2023-09-25",
      },
    ],
    isNew: true,
    featured: false,
    trending: true,
    createdAt: "2023-07-10",
  },
  {
    id: "smart-3",
    name: "FitTrack Smart Scale",
    description: "Advanced smart scale that measures 17 body metrics",
    fullDescription:
      "The FitTrack Smart Scale goes beyond weight to give you a complete picture of your health. It measures 17 body metrics, including weight, BMI, body fat percentage, muscle mass, and more. The scale syncs wirelessly with the FitTrack app, allowing you to track your progress over time and set goals. With support for unlimited users, the whole family can track their health journey. The sleek, modern design and tempered glass platform make it a stylish addition to any bathroom.",
    price: 3499,
    originalPrice: 3999,
    discount: 13,
    rating: 4.5,
    stock: 60,
    sold: 110,
    category: "Smart Gadgets",
    brand: "FitTrack",
    sku: "FT-SS-003",
    images: [
      "https://images.pexels.com/photos/4792733/pexels-photo-4792733.jpeg?auto=compress&cs=tinysrgb&w=1260&h=750&dpr=2",
      "https://images.pexels.com/photos/4792732/pexels-photo-4792732.jpeg?auto=compress&cs=tinysrgb&w=1260&h=750&dpr=2",
      "https://images.pexels.com/photos/4792731/pexels-photo-4792731.jpeg?auto=compress&cs=tinysrgb&w=1260&h=750&dpr=2",
      "https://images.pexels.com/photos/4792730/pexels-photo-4792730.jpeg?auto=compress&cs=tinysrgb&w=1260&h=750&dpr=2",
    ],
    features: [
      "Measures 17 body metrics",
      "Syncs with FitTrack app",
      "Supports unlimited users",
      "Auto-recognition technology",
      "High-precision sensors",
      "Tempered glass platform",
      "Rechargeable battery",
      "Works with fitness apps",
    ],
    specifications: {
      Metrics:
        "Weight, BMI, Body Fat, Muscle Mass, Water Percentage, Bone Mass, Protein, BMR, Visceral Fat, Subcutaneous Fat, Standard Weight, Weight Control, Body Age, Fat Weight, Muscle Weight, Protein Mass, Metabolic Age",
      Capacity: "5-180kg (11-400lbs)",
      Accuracy: "±0.1kg (±0.2lbs)",
      Power: "Rechargeable battery (USB-C)",
      Connectivity: "Bluetooth 5.0",
      "App Compatibility": "iOS 9.0+, Android 5.0+",
      Dimensions: "300 x 300 x 25 mm",
      Material: "Tempered glass and ABS plastic",
      Display: "LED display",
      "User Profiles": "Unlimited",
    },
    reviews: [
      {
        id: "r43",
        name: "Quinn P.",
        rating: 4,
        comment: "Great scale with comprehensive metrics. The app is well-designed and makes tracking progress easy.",
        date: "2023-11-05",
      },
      {
        id: "r44",
        name: "Zara M.",
        rating: 5,
        comment: "The multiple user support is perfect for our family. The measurements seem accurate and consistent.",
        date: "2023-10-12",
      },
      {
        id: "r45",
        name: "Wyatt B.",
        rating: 4,
        comment:
          "Good value for the features. The body composition metrics help me track my fitness journey beyond just weight.",
        date: "2023-09-20",
      },
    ],
    isNew: false,
    featured: true,
    trending: false,
    createdAt: "2023-05-25",
  },
  // New Arrivals - Smart Gadgets
  {
    id: "smart-4",
    name: "SmartHome Security Camera",
    description: "Wireless security camera with 2K resolution and AI detection",
    fullDescription:
      "Keep your home safe with the SmartHome Security Camera. This wireless camera captures crystal-clear 2K video and uses AI to distinguish between people, vehicles, and animals, reducing false alerts. With color night vision, you can see details even in the dark. The weatherproof design makes it suitable for both indoor and outdoor use, while the rechargeable battery eliminates the need for wiring. Access live and recorded footage through the SmartHome app from anywhere.",
    price: 4999,
    originalPrice: 5999,
    discount: 17,
    rating: 5.0,
    stock: 45,
    sold: 75,
    category: "Smart Gadgets",
    brand: "SmartHome",
    sku: "SH-SC-004",
    images: [],
    features: [
      "2K video resolution",
      "AI person, vehicle, and animal detection",
      "Color night vision",
      "Weatherproof design (IP65)",
      "Rechargeable battery (up to 6 months)",
      "Two-way audio",
      "Local and cloud storage options",
      "Works with Alexa and Google Assistant",
    ],
    specifications: {
      Resolution: "2K (2560 x 1440)",
      "Field of View": "160° diagonal",
      "Night Vision": "Color night vision up to 25 feet",
      Audio: "Full-duplex two-way audio with noise cancellation",
      "Weather Resistance": "IP65 (dust-tight and water-resistant)",
      Battery: "Rechargeable 6500mAh, up to 6 months per charge",
      Storage: "microSD card slot (up to 128GB), optional cloud storage",
      Connectivity: "2.4GHz Wi-Fi",
      Dimensions: "89 x 52 x 84.5 mm",
      Weight: "365g",
      "Operating Temperature": "-20°C to 45°C",
    },
    reviews: [
      {
        id: "r46",
        name: "Victor R.",
        rating: 5,
        comment:
          "The video quality is excellent and the AI detection works well. I no longer get alerts for every passing car.",
        date: "2023-11-10",
      },
      {
        id: "r47",
        name: "Penelope S.",
        rating: 5,
        comment: "Easy to install and the battery life is impressive. The app is intuitive and responsive.",
        date: "2023-10-18",
      },
      {
        id: "r48",
        name: "Isaac T.",
        rating: 5,
        comment:
          "Great security camera for the price. The color night vision is a game-changer for identifying details.",
        date: "2023-09-25",
      },
    ],
    isNew: true,
    featured: false,
    trending: true,
    createdAt: "2023-10-10",
  },

  // New Arrivals - Accessories
  {
    id: "accessory-4",
    name: "ProSound Noise-Cancelling Headphones",
    description: "Premium wireless headphones with adaptive noise cancellation",
    fullDescription:
      "Experience immersive sound with the ProSound Noise-Cancelling Headphones. These premium headphones feature adaptive noise cancellation that adjusts to your environment, blocking out distractions so you can focus on your music. The plush ear cushions and lightweight design ensure comfort during extended listening sessions, while the 40-hour battery life keeps the music going all day. With high-resolution audio support and a built-in equalizer, you can customize the sound to your preferences.",
    price: 12999,
    originalPrice: 14999,
    discount: 13,
    rating: 4.8,
    stock: 35,
    sold: 60,
    category: "Accessories",
    brand: "ProSound",
    sku: "PS-NC-001",
    images: [
      "https://images.pexels.com/photos/577769/pexels-photo-577769.jpeg?auto=compress&cs=tinysrgb&w=1260&h=750&dpr=2",
      "https://images.pexels.com/photos/1649771/pexels-photo-1649771.jpeg?auto=compress&cs=tinysrgb&w=1260&h=750&dpr=2",
      "https://images.pexels.com/photos/3394666/pexels-photo-3394666.jpeg?auto=compress&cs=tinysrgb&w=1260&h=750&dpr=2",
      "https://images.pexels.com/photos/3780681/pexels-photo-3780681.jpeg?auto=compress&cs=tinysrgb&w=1260&h=750&dpr=2",
    ],
    features: [
      "Adaptive noise cancellation",
      "40-hour battery life",
      "Plush ear cushions",
      "High-resolution audio",
      "Built-in equalizer",
      "Bluetooth 5.2",
      "Voice assistant support",
      "Foldable design",
    ],
    specifications: {
      "Driver Size": "40mm dynamic drivers",
      "Frequency Response": "20Hz - 40kHz",
      Connectivity: "Bluetooth 5.2, 3.5mm audio jack",
      Codecs: "SBC, AAC, aptX HD, LDAC",
      "Battery Life": "40 hours (ANC on), 60 hours (ANC off)",
      Charging: "USB-C, 10 minutes charge for 5 hours playback",
      Weight: "250g",
      "Noise Cancellation": "Adaptive ANC with ambient mode",
      Microphones: "8 microphones for calls and ANC",
      Controls: "Touch controls, physical buttons",
      "Water Resistance": "IPX4",
    },
    reviews: [
      {
        id: "r52",
        name: "Marcus L.",
        rating: 5,
        comment: "The noise cancellation is incredible. I can't hear anything around me when I'm listening to music.",
        date: "2023-11-18",
      },
      {
        id: "r53",
        name: "Sophia J.",
        rating: 5,
        comment: "The sound quality is amazing and the comfort is unmatched. I can wear these all day.",
        date: "2023-11-05",
      },
      {
        id: "r54",
        name: "Daniel R.",
        rating: 4,
        comment: "Great headphones with excellent battery life. The app could use some improvements though.",
        date: "2023-10-22",
      },
    ],
    isNew: true,
    featured: true,
    trending: true,
    createdAt: "2023-10-05",
  },
]

// Mock Philippine locations data
const philippineLocations: PhilippineLocation[] = [
  {
    islandGroup: "Luzon",
    name: "National Capital Region (NCR)",
    provinces: [
      {
        name: "Metro Manila",
        municipalities: [
          {
            name: "Manila",
            barangays: [
              "Binondo",
              "Ermita",
              "Intramuros",
              "Malate",
              "Quiapo",
              "Sampaloc",
              "San Nicolas",
              "Santa Cruz",
              "Tondo",
            ],
          },
          {
            name: "Quezon City",
            barangays: [
              "Bagong Silangan",
              "Batasan Hills",
              "Commonwealth",
              "Fairview",
              "Kamuning",
              "Katipunan",
              "Cubao",
              "Diliman",
              "Loyola Heights",
            ],
          },
          {
            name: "Makati",
            barangays: [
              "Ayala Avenue",
              "Bel-Air",
              "Dasmariñas",
              "Forbes Park",
              "Poblacion",
              "Rockwell",
              "San Lorenzo",
              "Urdaneta",
              "Valenzuela",
            ],
          },
          {
            name: "Pasig",
            barangays: [
              "Bagong Ilog",
              "Kapitolyo",
              "Manggahan",
              "Ortigas Center",
              "San Antonio",
              "Santolan",
              "Ugong",
              "Valle Verde",
            ],
          },
        ],
      },
    ],
  },
  {
    islandGroup: "Luzon",
    name: "Cordillera Administrative Region (CAR)",
    provinces: [
      {
        name: "Benguet",
        municipalities: [
          {
            name: "Baguio City",
            barangays: [
              "Asin Road",
              "Camp 7",
              "City Camp",
              "Engineers Hill",
              "Fairview",
              "Loakan",
              "Mines View",
              "Pacdal",
              "Scout Barrio",
            ],
          },
          {
            name: "La Trinidad",
            barangays: ["Balili", "Betag", "Lubas", "Pico", "Poblacion", "Puguis", "Shilan", "Tawang"],
          },
        ],
      },
      {
        name: "Ifugao",
        municipalities: [
          {
            name: "Banaue",
            barangays: ["Amganad", "Bocos", "Gohang", "Poblacion", "Poitan", "View Point"],
          },
        ],
      },
    ],
  },
  {
    islandGroup: "Visayas",
    name: "Western Visayas",
    provinces: [
      {
        name: "Iloilo",
        municipalities: [
          {
            name: "Iloilo City",
            barangays: ["Arevalo", "City Proper", "Jaro", "La Paz", "Lapuz", "Mandurriao", "Molo"],
          },
          {
            name: "Oton",
            barangays: ["Alegre", "Bita", "Botong", "Cagbang", "Poblacion", "San Antonio", "Trapiche"],
          },
        ],
      },
      {
        name: "Cebu",
        municipalities: [
          {
            name: "Cebu City",
            barangays: ["Apas", "Banilad", "Capitol Site", "Lahug", "Mabolo", "Poblacion", "Talamban", "Tisa"],
          },
          {
            name: "Mandaue City",
            barangays: [
              "Alang-Alang",
              "Banilad",
              "Cabancalan",
              "Centro",
              "Guizo",
              "Ibabao",
              "Looc",
              "Maguikay",
              "Tipolo",
            ],
          },
        ],
      },
    ],
  },
  {
    islandGroup: "Mindanao",
    name: "Davao Region",
    provinces: [
      {
        name: "Davao del Sur",
        municipalities: [
          {
            name: "Davao City",
            barangays: ["Buhangin", "Catalunan Grande", "Matina", "Mintal", "Poblacion", "Talomo", "Toril", "Tugbok"],
          },
          {
            name: "Digos City",
            barangays: ["Aplaya", "Cogon", "Dawis", "Matti", "Poblacion", "San Jose", "Sinawilan", "Tres de Mayo"],
          },
        ],
      },
      {
        name: "Davao Oriental",
        municipalities: [
          {
            name: "Mati City",
            barangays: ["Badas", "Central", "Dahican", "Dawan", "Libudon", "Macambol", "Sainz", "Taguibo"],
          },
        ],
      },
    ],
  },
]

// Mock order data
const orders: Order[] = [
  {
    id: "ORD123456",
    date: "November 15, 2023",
    status: "processing",
    items: [
      {
        id: "item1",
        name: "TechPro UltraBook X5",
        price: 65999,
        quantity: 1,
        image: "https://images.pexels.com/photos/18105/pexels-photo.jpg?auto=compress&cs=tinysrgb&w=80&h=80&dpr=2",
      },
      {
        id: "item2",
        name: "SoundWave Pro Wireless Earbuds",
        price: 8999,
        quantity: 1,
        image:
          "https://images.pexels.com/photos/3780681/pexels-photo-3780681.jpeg?auto=compress&cs=tinysrgb&w=80&h=80&dpr=2",
      },
    ],
    subtotal: 74998,
    tax: 9000,
    shipping: 0,
    total: 83998,
    paymentMethod: "gcash",
    address: {
      fullName: "Juan Dela Cruz",
      phone: "09123456789",
      email: "juan@example.com",
      street: "123 Rizal Street",
      barangay: "Poblacion",
      municipality: "Makati",
      province: "Metro Manila",
      region: "National Capital Region (NCR)",
      postalCode: "1200",
    },
  },
  {
    id: "ORD789012",
    date: "November 10, 2023",
    status: "shipped",
    items: [
      {
        id: "item3",
        name: "PixelMax Pro 5G",
        price: 54999,
        quantity: 1,
        image:
          "https://images.pexels.com/photos/47261/pexels-photo-47261.jpeg?auto=compress&cs=tinysrgb&w=80&h=80&dpr=2",
      },
    ],
    subtotal: 54999,
    tax: 6600,
    shipping: 150,
    total: 61749,
    paymentMethod: "card",
    address: {
      fullName: "Maria Santos",
      phone: "09187654321",
      email: "maria@example.com",
      street: "456 Bonifacio Avenue",
      barangay: "Bagong Silangan",
      municipality: "Quezon City",
      province: "Metro Manila",
      region: "National Capital Region (NCR)",
      postalCode: "1119",
    },
  },
  {
    id: "ORD345678",
    date: "November 5, 2023",
    status: "delivered",
    items: [
      {
        id: "item4",
        name: "SmartWatch Pro 5",
        price: 12999,
        quantity: 1,
        image:
          "https://images.pexels.com/photos/437037/pexels-photo-437037.jpeg?auto=compress&cs=tinysrgb&w=80&h=80&dpr=2",
      },
      {
        id: "item5",
        name: "PowerBank Ultra 26800mAh",
        price: 3499,
        quantity: 2,
        image:
          "https://images.pexels.com/photos/4526407/pexels-photo-4526407.jpeg?auto=compress&cs=tinysrgb&w=80&h=80&dpr=2",
      },
    ],
    subtotal: 19997,
    tax: 2400,
    shipping: 0,
    total: 22397,
    paymentMethod: "cod",
    address: {
      fullName: "Antonio Reyes",
      phone: "09198765432",
      email: "antonio@example.com",
      street: "789 Lapu-Lapu Street",
      barangay: "Lahug",
      municipality: "Cebu City",
      province: "Cebu",
      region: "Western Visayas",
      postalCode: "6000",
    },
  },
]

/**
 * Get all products
 */
export async function getProducts(filters?: Record<string, any>): Promise<Product[]> {
  try {
    return await productApi.getProducts(filters);
  } catch (error) {
    console.error("Error fetching products from API:", error);
    // Fallback to static data
    return products;
  }
}

/**
 * Get a product by ID
 */
export async function getProductById(id: string): Promise<Product | undefined> {
  try {
    return await productApi.getProductById(id);
  } catch (error) {
    console.error(`Error fetching product ${id} from API:`, error);
    // Fallback to static data
    return products.find((product) => product.id === id);
  }
}

export function getPhilippineLocations(): PhilippineLocation[] {
  return philippineLocations
}
